sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: 
  - npm
  - node_modules
branches:
  only:
    - source # build source branch only
before_script:
  - export TZ=America/Montreal # set the correct timezone on the machine
  - git submodule update --init # fetch my theme's code which is linked as a submodule
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  keep_history: true # keep git history instead of force pushing a new one
  target_branch: master # deploy to master (from source)
  on:
    branch: source # allow deployment from source branch only
  local-dir: public # files to push are located in public/ folder